### ISSUE TITLE
Refactor goto 

### ISSUE THREAD

**Issue by technocake** [technocake/goto#103]
I'm currently working on refactoring the logic around storage to be centered around passing the project name only, and let the internal details be dealt with behind the hood. But inside python-land, and not in shell-land. 

Rationale: 
  
- Support different scopes for shortcuts:
    - private
    - shared
    - public

- cleaner setup

And of course in this process of implementing this I've been addressing some other issues. Like #41 unicode issues deleting entire project file.

This makes the `GotoMagic` do a bit more inside the project land. 
Like creating folders and json files for each scope.

**Comment by Arxcis** [comment]
Could you elaborate what the different scopes mean?

- Private - Project scope
- Shared - Shared between projects?
- Public - ?

**Comment by technocake** [comment]
Private = your magicwords, locally (but might be pushed somewhere remote if ypu wish). They are meant for you and you only. 

Shared = shared with others

Public = hosted in a public  goto repo somewhere

**Comment by technocake** [comment]
The refactoring has been done. What is left is to enable git to the whole thing. that should be further discussed in its own issue
