### ISSUE TITLE
Truncated filepath with spaces - syntax error: Expected “"” but found end of script. (-2741)

### ISSUE THREAD

**Issue by Arxcis** [technocake/goto#113]
This does not work with both single quotes and double quotes around the filepath.
Also tried both with relative path and absolute path.
```
$ goto update universe '/User/jonasjso/Library/Application\ Support/Steam/steamapps/common/Universe\ Sandbox\ 2/Universe\ Sandbox.app'
Updated magic word universe

$ goto universe
51:51: syntax error: Expected “"” but found end of script. (-2741)
176:176: syntax error: Expected “"” but found end of script. (-2741)
177:177: syntax error: Expected “"” but found end of script. (-2741)
176:176: syntax error: Expected “"” but found end of script. (-2741)

$ goto show universe
/User/jonasjso/Library/Application\
```

As you can see, the filepath is truncated
Also for some reasone `firefox` opens up, even if it is not the default browser. Hmm..

**Comment by technocake** [comment]
single quotes will not expand escaped expressions. so the escaped spaces: `\ ` will be given to goto as written. that is the cause of the error here. 

Goto has a funny response though, but input given would work more like intended if wrapped with double quotes.

Although, goto has an issue with arguments containing space in general. I belive there is a related issue on that

**Comment by Arxcis** [comment]
@technocake I am sorry but "-quotes does not make a difference
```
$  goto update universe "/User/jonasjso/Library/Application\ Support/Steam/steamapps/common/Universe\ Sandbox\ 2/Universe\ Sandbox.app"
Updated magic word universe

$ goto show universe
/User/jonasjso/Library/Application\

**Comment by technocake** [comment]
It made a difference, it didnt get the syntax errors. 

The issue with the chopped of path is another issue - it is not related with quotes in any other way than perhaps missing a pair or two internally somewhere ^^

**Comment by technocake** [comment]
See related issue #105

**Comment by Arxcis** [comment]
True this is a duplicate of #105 . Hehe
