### ISSUE TITLE
goto cd code - nothing happens

### ISSUE THREAD

**Issue by Arxcis** [technocake/goto#15]
```
jonas in ~
$ project goto
active project is now: goto

jonas in ~
$ goto cd code    # <--- nothing happens

jonas in ~
$ goto list -v
            code --> /usr/local/opt/goto
            goto --> https://github.com/technocake/goto
          github --> https://github.com/technocake/goto
```

**Comment by Arxcis** [comment]
During installation `source start_goto` was appended to `.bash_aliases` but on Ubuntu 18.04  `.bashrc` is the default terminal config file. To fix manually append `source start_goto` to `.bashrc`, then restart terminal.

**Comment by technocake** [comment]
This issue should now be resolved, since it is now more up to the user to make sure that something sources the goto startup script.
