### ISSUE TITLE
Installing goto on my Windows workstation - can't open file the_real_goto.py

### ISSUE THREAD

**Issue by Arxcis** [technocake/goto#2]
- On windows I just want to put the `goto/bin` folder in PATH using the Start Menu > Environment Variables GUI, since it is the least error prone way. I clone goto to my github folder, and then just add `goto/bin` to PATH as is, without moving it to some special place on the computer. Also without running the install script.

- This leads to a problem with a wrongcoded path when I run `goto` the first time
```
$ cmd //c cd
P:\git\technocake\goto

$ goto list
(null): can't open file 'C:/Program Files/Git/usr/local/opt/goto/the_real_goto.py': [Errno 2] No such file or directory
```

**Comment by technocake** [comment]
Thanks for a very good and detailed issue. First: Have you tested the windows branch or the master branch?

**Comment by technocake** [comment]
in the windows branch I believe I fixed this issue.Not able to test right now. and also see the windows install script https://github.com/technocake/goto/blob/windows/install_goto.bat

**Comment by Arxcis** [comment]
Ok, I see. I will give it another try tomorrow ;)

**Comment by Arxcis** [comment]
Testing this later today. Re-opening if it does not solve my issue. Thanks! 👍
