### ISSUE TITLE
install fails if username has space

### ISSUE THREAD

**Issue by technocake** [technocake/goto#26]
Goto fails on step to create ./goto in the home folder if the user has a space in the username.

Fix: add "" around the home folder variable...

**Comment by Arxcis** [comment]
There is a similar bug when `goto add <magic> <filepaths with a space>`. Does not work currently

**Comment by technocake** [comment]
That is actually a standard bash behaviour. All unix commands have tokens separated with the delimiter space. If one token is meant to be a string containing spaces, it must be encapsulated with "<path with space>"

**Comment by Arxcis** [comment]
Ah of course. Nevermind.. We should keep the bash tradition

**Comment by technocake** [comment]
commit https://github.com/technocake/goto/commit/bc8cad7c7798c2c029b9230a556fd664a2e7553d should fix this now - awaiting testing
