### ISSUE TITLE
goto add <magic> <filepaths with a space> cuts of at first space

### ISSUE THREAD

**Issue by Arxcis** [technocake/goto#28]

**Comment by technocake** [comment]
yes, but this is a bash issue. Encapsulate filepaths who have space with "

**Comment by technocake** [comment]
possible solution also:

if command == 'add':
   uri=' '.join(sys.argv[3:])

**Comment by Arxcis** [comment]
We should demand that the user encapsulate things with space with "".
Yes it is a possible solution, but it violates a core convention, so we should at least think about it for a while.
