### ISSUE TITLE
source start_goto in zsh breaks $PATH

### ISSUE THREAD

**Issue by haakonmb** [technocake/goto#37]
After installing goto and adding `source start_goto` to .zshrc, when restarting zsh, several normal commands are not recognized and $PATH seems to be polluted. 
<img width="411" alt="screen shot 2018-10-05 at 20 36 31" src="https://user-images.githubusercontent.com/7099302/46553694-77065a00-c8de-11e8-8079-a08b64ba878c.png">

**Comment by haakonmb** [comment]
Additionally, when removing the zsh bash emulation autocompletion for `start_goto` it complains about line 24 and 29 in start_goto.
<img width="318" alt="screen shot 2018-10-05 at 20 39 56" src="https://user-images.githubusercontent.com/7099302/46553903-0a3f8f80-c8df-11e8-9d49-7c072ff9e915.png">

**Comment by technocake** [comment]
Running with echo of commands reveals `complete:13: command not found: compdef`.
Command to reproduce: `zsh -x -c "source start_goto"`

Seems to be related to the order of importing zsh completion and  bash completion compatibility functions in zsh. Issue is knowin in oh-my-zsh:  https://github.com/robbyrussell/oh-my-zsh/issues/3356

**Comment by technocake** [comment]
Hehehehe :)  I found the cause:

`+/Library/Frameworks/Python.framework/Versions/3.6/bin/goto:54> path=$'\nAh hoy!\n\n    - The Magic word list does not exist.\n\n `

So from this point and on, all shell scripts will use `local` variables consistently.
The solution is also to not use path as a variable name. In zsh it is case-insensitive.

**Comment by technocake** [comment]
Starting from goto version `1.4.3` and above, this issue is no longer present :)
