### ISSUE TITLE
goto add <magiword> <directorypath>, not working with relative and absolute paths

### ISSUE THREAD

**Issue by Arxcis** [technocake/goto#4]
**Problem** - I am standing in my project directory, and I want to add a shortcut to the root of my project.

**Experience**
```
jonasjso in ~/git/kvalitetskontroll/kk-vue-components on master
$ project kk-vue-components
active project is now: kk-vue-components

jonasjso in ~/git/kvalitetskontroll/kk-vue-components on master
$ goto add root .
Added magic word root

jonasjso in ~
$ goto root

jonasjso in ~  # < --- still in home directory
$
```
... This was just using the path `.`. Maybe a less relative path will work
```
jonasjso in ~
$ goto add root ~/git/kvalitetskontroll/kk-vue-components
Added magic word root

jonasjso in ~
$ goto root

jonasjso in ~  # < --- still in home directory
$
```
... Still no luck. I will try with full path this time.
```
jonasjso in ~/git/kvalitetskontroll/kk-vue-components on master
$ goto add root /Users/jonasjso/git/kvalitetskontroll/kk-vue-components
Added magic word root

jonasjso in ~
$ goto root

jonasjso in ~  # < --- still in home directory
$
```
What am I missing here?

**Comment by technocake** [comment]
Thanks!  - This should be trivial to implement using `os.path.abspath` -- jumping straight into it

**Comment by Arxcis** [comment]
Confirm that this is working on Ubuntu 18.04
![works](https://user-images.githubusercontent.com/3092618/45590882-bd057900-b943-11e8-902e-f014614fcd65.png)
