### ISSUE TITLE
goto add - Always be explicit of which protocol you are using (URL) to access resource

### ISSUE THREAD

**Issue by Arxcis** [technocake/goto#40]
Example: 
```
goto add local file:///home/<user>/github/goto
goto add github https://github.com/<user>/goto
```
For a cleaner look  we could allow to ommit the double `//` like so
```
goto add local file:/home/<user>/github/goto
goto add github https:github.com/<user>/goto
```
...or maybe even better
```
goto add local file /home/<user>/github/goto
goto add github https github.com/<user>/goto
```

**Comment by technocake** [comment]
I think this is good for all cases except file paths - because we are making a cli tool - and the standard input format of the filesystem paths is without protocol/scheme.

**Comment by Arxcis** [comment]
> I think this is good for all cases except file paths - because we are making a cli tool - and the standard input format of the filesystem paths is without protocol/scheme.

Good point. Maybe prefix `file://` for the internal data then, or something else entirely.

**Comment by technocake** [comment]
This is how the current implementation works - it requires explicit scheme for all other protocols then files and directories. 

I am a bit unsure about the `file://` scheme - my concern is about how different OS and platforms handles it. We might do it.

There is one issue now, that if a shortcut points to a file or folder, and that file or folder is removed, goto will call `open` (osx), `xdg-open` (linux)  and `start in windows`. Result is quite random. 

However I regard the intention of this discussion to be implemented and thus closing this issue.
