### ISSUE TITLE
install_goto with zsh prompts for wrong rcfile

### ISSUE THREAD

**Issue by sirkro** [technocake/goto#56]
install_goto should check for current shell and not if .bash_profile exists and so on.

Ex.
if current shell == Bash ?
else if current shell == Zsh?
else current shell is not supported

**Comment by technocake** [comment]
I have a fix for this now - I am working on other issues with pyenv and zsh -- I will publish it with those changes.

**Comment by technocake** [comment]
Starting from goto version `1.4.3`, If your default shell is `zsh`,  the  `install_goto` will prompt you to add the initialization lines to `.zshrc`. 

However, still, if you have `bash` as the default shell, it will prompt for `.bash_profile`.
If choosing `n` when asked,  instructions on what to add to your rcfile manually is given.

**Comment by technocake** [comment]
Further implications is discovered - your systems default shell affects behaviour of the goto scripts.  

If default shell is `bash` - as it is in osx/ most linux distros, all the shell scripts: `install_goto` `start_goto` `goto` `project` etc will run in bash, even when invoked from `zsh`. 

To solve this, she-bangs are called for - and some inteligent discovery of the invoking shell.

**Comment by technocake** [comment]
Version 1.5.0 of goto now fixes this issue. Feel free to upgrade @sirkro  `pip install --upgrade magicgoto` ^^
