### ISSUE TITLE
add slack plugin that allows to goto slack channels

### ISSUE THREAD

**Issue by technocake** [technocake/goto#64]
If working in an environment where you have project specific slack channels, it would be a nice feature to be able to add slack shortcuts pointing directly to those.

`goto add slack slack://companyslack.slack.com/#prjoject-x`

Then running the command `goto slack` would open slack in that channel.

**Comment by Arxcis** [comment]
Opening slack channels already works today
Here are some of my shortcuts that works today.
```
$ goto show technocake
slack://channel?team=T4TF3258S&id=DCABXL0NL    # Opens the private message channel with the use techocake

$ goto show development
slack://channel?team=T4TE3258S&id=G4U6D6V0S  #Opens the team channel development
```
 What found too difficult is getting the correct ids. I had to scrape channel ids from web-version urls, and i scraped the team-id from the web-versions source. Not ideal.

Ref: https://api.slack.com/docs/deep-linking#open_a_channel

**Comment by technocake** [comment]
If someone wants to so this, we will gladly reopen this issue. closing for now

**Comment by Arxcis** [comment]
I think this would require some sort of authentication, together with API calls, if we are to figure out which project name belongs to which project id.
