### ISSUE TITLE
Installation issue on zsh 

### ISSUE THREAD

**Issue by HussamYousif** [technocake/goto#69]
Issues installing goto: 

![image](https://user-images.githubusercontent.com/2606325/59017209-4c8ce800-8843-11e9-8aa4-6ae375536e16.png)

on the following system:

![image](https://user-images.githubusercontent.com/2606325/59017241-5c0c3100-8843-11e9-86e2-1805c96c4a6c.png)

custom settings on .zshrc

![image](https://user-images.githubusercontent.com/2606325/59017290-76dea580-8843-11e9-8a08-e9723c3a68ee.png)

**Comment by technocake** [comment]
#78 Fixes this issue :) @HussamYousif  Feel free to try: 
`pip install --upgrade magicgoto`

**Comment by HussamYousif** [comment]
Thank you :)
